packages:
  - apps/*
  - packages/*
  - tooling
minimumReleaseAge: 0
allowBuilds:
  '@firebase/util': false
  bcrypt: true
  esbuild: true
  lefthook: true
  msgpackr-extract: true
  msw: true
  protobufjs: false
  sharp: true
overrides:
  '@better-auth/infra>@better-fetch/fetch': 1.3.2
  esbuild@>=0.17.0 <0.28.1: ^0.28.1
  esbuild@>=0.27.3 <0.28.1: ^0.28.1
  postcss@<8.5.10: ^8.5.14
  samlify@<2.13.0: ^2.13.0
  uuid@<11.1.1: ^11.1.1
patchedDependencies:
  '@react-pdf/layout@5.2.0': patches/@react-pdf__layout@5.2.0.patch
  '@react-pdf/textkit': patches/@react-pdf__textkit.patch
  fontkit@2.0.4: patches/fontkit@2.0.4.patch
  react-pdf-html@2.1.5: patches/react-pdf-html@2.1.5.patch
